### ISSUE TITLE
conda install does not contain the new simulations

### ISSUE THREAD

**Issue by aauss** [JarnoRFB/epysurv#28]
I just conda installed epysurv. However, the new simulation algorithms are not contained.

**Comment by JarnoRFB** [comment]
For this we first need to make a new release on github. However, let's get #27 merged first. Meanwhile you could run something like `conda build .` in the repository to install it from source.

**Comment by aauss** [comment]
Thanks, yeah I will then use `conda build` in the meanwhile. Looking forward to the review. We then can talk about the release some time soon. I have a PyTorch-based outbreak simulation algorithm in the loop. Maybe we want to include it, maybe PyTorch is too large of a dependency.
