### ISSUE TITLE
Expose other useful columns like 'upperbound'

### ISSUE THREAD

**Issue by burgersmoke** [JarnoRFB/epysurv#34]
I noticed in using the package that columns like 'alarm' are exposed but other helpful columns like 'upperbound' are not exposed.  This can be helpful to see in visualizations and to see why there was or was not an alarm.

I have a pull request ready for this.  I'll link it in a moment.

**Comment by burgersmoke** [comment]
Pull request for this is ready and passing.  I think this will be a helpful addition as I know it has been for my purposes.

**Comment by JarnoRFB** [comment]
Closed by #35
