### ISSUE TITLE
Fix broken conda feedstock pipeline

### ISSUE THREAD

**Issue by justinshenk** [JarnoRFB/epysurv#37]
Feedstock (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=350396&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642) breaks on `pickle.load`: https://github.com/JarnoRFB/epysurv/blob/d031511cbe5d5c66c3d035b21e1b7cd32b4ae6c9/tests/conftest.py#L46

As per https://stackoverflow.com/a/68342039/6256888, the recommended workaround is to replace `pickle.load` with `pandas.read_pickle` for pandas v1.3.0.

**Comment by JarnoRFB** [comment]
Thanks for looking that up! I'll try to fix it.
