### ISSUE TITLE
Fix conda-forge build

### ISSUE THREAD

**Issue by justinshenk** [JarnoRFB/epysurv#9]
Version conflict for windows Python packages on [conda-forge PR](https://github.com/conda-forge/staged-recipes/pull/8237):
(https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/24230568)

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.7 -> vc[version='>=14,<15.0a0']
  - vc=9
Use "conda search <package> --info" to see the dependencies for each package.
During handling of the above exception, another exception occurred:
`conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {"vc[version='>=14,<15.0a0']", 'vc=9'}`
```

**Comment by JarnoRFB** [comment]
Maybe we need to add this to the `build` section

```
 build:
     track_features:
         - vc14           [win]
```
?

**Comment by justinshenk** [comment]
Good idea. I excluded windows from the current build to get it setup, and it passed (https://github.com/conda-forge/staged-recipes/pull/8237). We can add this after it is merged.
